const getters = {
  sidebar: state => state.app.sidebar,
  language: state => state.app.language,
  size: state => state.app.size,
  device: state => state.app.device,
  visitedViews: state => state.tagsView.visitedViews,
  cachedViews: state => state.tagsView.cachedViews,
  token: state => state.user.token,
  dicts: state => state.dict.dicts,
  pageArray: state => state.dict.pageArray,
  defaultPageSize: state => state.dict.defaultPageSize,
  avatar: state => state.user.avatar,
  name: state => state.user.name,
  introduction: state => state.user.introduction,
  status: state => state.user.status,
  roles: state => state.user.roles,
  setting: state => state.user.setting,
  info: state => state.user.info,
  permission_routes: state => state.permission.routes,
  permission_menus: state => state.permission.menus,
  addRoutes: state => state.permission.addRoutes,
  fetchRoutes: state => state.permission.fetchRoutes,
  permissions: state => state.permission.permissions,
  errorLogs: state => state.errorLog.logs
}
export default getters
